### ISSUE TITLE
Align JUnit versions

### ISSUE THREAD

**Issue by sormuras** [jetty-project/junit-issue-801#1]
Does not help with the main issue https://github.com/junit-team/junit5/issues/801 but it's better not mixing versions:

https://github.com/jetty-project/junit-issue-801/blob/43ad28f0c4adf10bb337b71015bd035143f747ae/pom.xml#L19-L21

If snapshot, then all snaphots. :)

```xml
    <junit.vintage.version>5.2.0-SNAPSHOT</junit.vintage.version>
    <junit.jupiter.version>5.2.0-SNAPSHOT</junit.jupiter.version>
```

**Comment by joakime** [comment]
Done.
